## Project Euler Problem 2

##  Each new term in the Fibonacci sequence is generated by
##  adding the previous two terms.  By starting with 1 and 2,
##  the first 10 terms will be:
##
##      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
##  By considering the terms in the Fibonacci sequence whose
##  values do not exceed four million, find the sum of the even
##  valued terms.
##
##  Answer: 4613732

## Generate some Fibonacci Numbers
def Problem2():
    oldNum = 0
    curNum = 1
    newNum = 1
    total = 0

    while newNum <= 4000000:
        newNum = oldNum + curNum
        oldNum = curNum
        curNum = newNum

        ## If the number is even, add it to the total

        if newNum % 2 == 0:
            total = total + newNum

    return(total)


